# Generated by Django 3.0.6 on 2020-05-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='people',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
